spring.application.name=Management

# Yleinen portti sovellukselle
server.port=8080

# --- H2 Tietokannan Konfiguraatio (PYSYVYYS) ---
# Tiedostopohjainen tila, joka säilyttää tiedot:
spring.datasource.url=jdbc:h2:file:./data/digierko;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Dentapp
spring.datasource.password=admin

# PYSYVÄ DATA: 'update' säilyttää olemassa olevan datan.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- H2 Konsoli ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JWT Turvallisuusasetukset ---
# TÄMÄ ON SALAINEN AVAIN! TEE TÄSTÄ PIDEMPI TUOTANTOKÄYTÖSSÄ!
jwt.secret=944520970a921d017b35f29d20b601f78a74e57827e7d77b068c85785050f16e
# Tokenin voimassaoloaika (esim. 1 tunti = 3600000 ms)
jwt.expiration=3600000